version: '3.7'
services:
  redis1:
    image: redis:5.0.3
    container_name: redis1
    hostname: redis1
    labels:
      - "name=redis"
      - "mode=standalone"
    network_mode: host
    volumes:
      - ./redis.conf:/data/redis.conf
      - ./data:/data
    command: redis-server /data/redis.conf